package edsm

var evTypes map[string]bool

func init() {

	evt := map[string]bool{
		"ApproachSettlement":       true,
		"BackPack":                 true,
		"BackpackChange":           true,
		"BookTaxi":                 true,
		"BuyAmmo":                  true,
		"BuyDrones":                true,
		"BuyExplorationData":       true,
		"BuyTradeData":             true,
		"CancelTaxi":               true,
		"Cargo":                    true,
		"CargoDepot":               true,
		"CarrierJump":              true,
		"CodexEntry":               true,
		"CollectCargo":             true,
		"CommitCrime":              true,
		"CommunityGoal":            true,
		"CommunityGoalDiscard":     true,
		"CommunityGoalJoin":        true,
		"CommunityGoalReward":      true,
		"CrewHire":                 true,
		"Died":                     true,
		"Docked":                   true,
		"EjectCargo":               true,
		"EngineerContribution":     true,
		"EngineerCraft":            true,
		"EngineerProgress":         true,
		"FSDJump":                  true,
		"FSDTarget":                true,
		"FSSAllBodiesFound":        true,
		"FSSDiscoveryScan":         true,
		"FetchRemoteModule":        true,
		"Interdicted":              true,
		"Interdiction":             true,
		"JoinACrew":                true,
		"LoadGame":                 true,
		"Loadout":                  true,
		"Location":                 true,
		"MarketBuy":                true,
		"MarketSell":               true,
		"MaterialCollected":        true,
		"MaterialDiscarded":        true,
		"MaterialTrade":            true,
		"Materials":                true,
		"MiningRefined":            true,
		"MissionAbandoned":         true,
		"MissionAccepted":          true,
		"MissionCompleted":         true,
		"MissionFailed":            true,
		"MissionRedirected":        true,
		"Missions":                 true,
		"ModuleBuy":                true,
		"ModuleRetrieve":           true,
		"ModuleSell":               true,
		"ModuleSellRemote":         true,
		"MultiSellExplorationData": true,
		"NpcCrewPaidWage":          true,
		"PayBounties":              true,
		"PayFines":                 true,
		"PayLegacyFines":           true,
		"Powerplay":                true,
		"PowerplayCollect":         true,
		"PowerplayDefect":          true,
		"PowerplayDeliver":         true,
		"PowerplayFastTrack":       true,
		"PowerplayJoin":            true,
		"PowerplayLeave":           true,
		"PowerplaySalary":          true,
		"Progress":                 true,
		"Promotion":                true,
		"QuitACrew":                true,
		"Rank":                     true,
		"RedeemVoucher":            true,
		"RefuelAll":                true,
		"Repair":                   true,
		"RepairAll":                true,
		"Reputation":               true,
		"RestockVehicle":           true,
		"Resurrect":                true,
		"SAAScanComplete":          true,
		"Scan":                     true,
		"ScientificResearch":       true,
		"SearchAndRescue":          true,
		"SelfDestruct":             true,
		"SellDrones":               true,
		"SellExplorationData":      true,
		"SellShipOnRebuy":          true,
		"SetUserShipName":          true,
		"ShipLocker":               true,
		"ShipyardBuy":              true,
		"ShipyardSell":             true,
		"ShipyardSwap":             true,
		"ShipyardTransfer":         true,
		"StartUp":                  true,
		"Statistics":               true,
		"StoredShips":              true,
		"Synthesis":                true,
		"TechnologyBroker":         true,
		"USSDrop":                  true,
		"Undocked":                 true,
	}

	evTypes = evt
}

func acceptEvType(evType string) bool {

	if e, ok := evTypes[evType]; ok && e == true {
		return true
	}

	return false
}
